import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Navbar from './components/Navbar'
import styles from '../styles/Home.module.css'
import Pokemons from './components/Pokemons'
import PokemonsProvider from './context/pokemonContext'

const Home: NextPage = () => {
  
  return (
    <PokemonsProvider>
      <div className={styles.container}>
        <Head>
          <title>Pokemon App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>

        <main className={styles.main}>
          <Navbar />
          <Pokemons />
        </main>

        <footer className={styles.footer}>
          
        </footer>
      </div>
    </PokemonsProvider>
  )
}

export default Home
